name: Discord Commit Notifications

on:
  push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send commit info to Discord
        uses: Sniddl/discord-action@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Новый коммит от **${{ github.actor }}** в репозитории **${{ github.repository }}**"
          embed: '{
            "title": "${{ github.event.head_commit.message }}",
            "url": "${{ github.event.head_commit.url }}",
            "author": {
              "name": "${{ github.actor }}"
            }
          }'
